import { ArrowRight, CheckCircle2, ClipboardCheck, Clock3, Flame, FlaskConical } from 'lucide-react'
import { Link } from 'react-router-dom'
import { modules } from '../data'
import { formatStudyTime, useProgress } from '../hooks/useProgress'

export function Dashboard() {
  const { summary, modulePercent, completedLabCount, examAttempts, bestExamScore } = useProgress()
  const accuracy = summary.questionsAnswered ? Math.round((summary.correctAnswers / summary.questionsAnswered) * 100) : 0
  const stats = [[Flame, `${summary.streakDays} days`, 'Current streak'], [Clock3, formatStudyTime(summary.studyMinutes), 'Practice time'], [CheckCircle2, String(summary.questionsAnswered), 'Questions tried'], [ArrowRight, `${accuracy}%`, 'Accuracy']] as const
  return <>
    <section className="overflow-hidden rounded-3xl bg-navy-950 p-6 text-white sm:p-9"><p className="eyebrow">Welcome back, Glenn</p><div className="mt-3 grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><h1 className="max-w-2xl text-3xl font-black tracking-tight sm:text-5xl">Build exam confidence one topic at a time.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-300 sm:text-base">Choose a CCNA topic, answer focused questions, and use the explanations to strengthen weak areas.</p></div><Link to="/practice" className="inline-flex w-fit items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-navy-950 transition hover:bg-cyan-300">Start practicing <ArrowRight size={18}/></Link></div></section>
    <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(([Icon,value,label]) => <div className="card p-4 sm:p-5" key={label}><Icon className="text-cyan-500" size={21}/><p className="mt-3 text-2xl font-black text-navy-950">{value}</p><p className="text-xs font-semibold text-slate-500">{label}</p></div>)}</section>
    <section className="mt-6 card flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-700"><FlaskConical/></span><div className="flex-1"><p className="eyebrow">Hands-on skills</p><h2 className="mt-1 text-xl font-black text-navy-950">{completedLabCount} guided labs completed</h2><p className="mt-1 text-sm text-slate-500">Build and verify real Cisco configurations in Packet Tracer.</p></div><Link to="/labs" className="inline-flex items-center gap-2 self-start rounded-xl bg-navy-950 px-4 py-3 text-sm font-black text-white sm:self-auto">Open labs <ArrowRight size={17}/></Link></section>
    <section className="mt-6 card flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><ClipboardCheck/></span><div className="flex-1"><p className="eyebrow">Exam readiness</p><h2 className="mt-1 text-xl font-black text-navy-950">{examAttempts.length ? `${bestExamScore}% best mock score` : 'Take your first mock exam'}</h2><p className="mt-1 text-sm text-slate-500">20 weighted questions with a 30-minute timer and detailed review.</p></div><Link to="/exam" className="inline-flex items-center gap-2 self-start rounded-xl bg-navy-950 px-4 py-3 text-sm font-black text-white sm:self-auto">Open exam <ArrowRight size={17}/></Link></section>
    <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Exam blueprint</p><h2 className="mt-1 text-2xl font-black text-navy-950">Practice by domain</h2></div><Link to="/practice" className="text-sm font-bold text-cyan-600">View all</Link></div><div className="grid gap-4 md:grid-cols-2">{modules.map(({id,title,description,icon:Icon,accent}) => { const progress = modulePercent(id); return <Link to={`/practice/${id}`} className="card p-5 transition hover:-translate-y-0.5 hover:shadow-lg" key={id}><div className="flex gap-4"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${accent}`}><Icon size={21}/></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><h3 className="font-extrabold text-navy-950">{title}</h3><span className="text-xs font-bold text-slate-500">{progress}%</span></div><p className="mt-1 text-sm leading-5 text-slate-500">{description}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-cyan-400" style={{width:`${progress}%`}}/></div></div></div></Link>})}</div></section>
  </>
}
