import { ArrowRight, CheckCircle2, Circle, FlaskConical, Trophy } from 'lucide-react'
import { modules } from '../data'
import { PageHeader } from '../components/PageHeader'
import { useProgress } from '../hooks/useProgress'

export function Learn() {
  const { modulePercent } = useProgress()
  return <><PageHeader eyebrow="Structured learning" title="CCNA 200-301 modules" text="Follow the exam blueprint in a practical sequence. Each module will combine concise lessons, command references, and knowledge checks."/><div className="grid gap-4 md:grid-cols-2">{modules.map(({id,title,description,icon:Icon,accent},i) => { const progress=modulePercent(id); return <article className="card p-6" key={id}><div className={`grid h-12 w-12 place-items-center rounded-2xl ${accent}`}><Icon/></div><p className="mt-5 text-xs font-bold uppercase tracking-widest text-slate-400">Module {i+1}</p><h2 className="mt-1 text-xl font-black text-navy-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p><button className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-600">Open module <ArrowRight size={17}/></button><div className="mt-5 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-cyan-400" style={{width:`${progress}%`}}/></div></article>})}</div></>
}

export function Labs() { const labs=['Build a basic IPv4 LAN','Configure VLANs and trunks','Inter-VLAN routing','Single-area OSPFv2']; return <><PageHeader eyebrow="Hands-on practice" title="Configuration labs" text="Build confidence with guided Packet Tracer labs that move from topology setup to verification and troubleshooting."/><div className="space-y-3">{labs.map((lab,i)=><article className="card flex items-center gap-4 p-5" key={lab}><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 font-black text-amber-700">{i+1}</span><div className="flex-1"><h2 className="font-extrabold text-navy-950">{lab}</h2><p className="mt-1 text-xs font-semibold text-slate-500">{20+i*10} min · Beginner</p></div><FlaskConical className="text-slate-400"/></article>)}</div></> }

export function Practice() { return <><PageHeader eyebrow="Exam preparation" title="Practice with purpose" text="Short quizzes and timed mock exams will help you recall concepts, read command output, and identify weak areas."/><div className="grid gap-4 sm:grid-cols-2"><article className="card p-6"><Circle className="text-cyan-500"/><h2 className="mt-4 text-xl font-black">Quick quiz</h2><p className="mt-2 text-sm text-slate-600">10 questions · Untimed · Instant explanations</p><button className="mt-6 rounded-xl bg-navy-950 px-5 py-3 text-sm font-bold text-white">Start quiz</button></article><article className="card p-6"><Trophy className="text-amber-500"/><h2 className="mt-4 text-xl font-black">Mock exam</h2><p className="mt-2 text-sm text-slate-600">100 questions · 120 minutes · Exam simulation</p><button className="mt-6 rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">Coming soon</button></article></div></> }

export function Progress() {
  const { modulePercent } = useProgress()
  return <><PageHeader eyebrow="Your performance" title="Progress overview" text="See what you have completed and where to focus your next study session."/><div className="card p-6"><h2 className="text-xl font-black">Module completion</h2><div className="mt-6 space-y-5">{modules.map(({id,title}) => { const progress=modulePercent(id); return <div key={id}><div className="flex justify-between text-sm font-bold"><span>{title}</span><span>{progress}%</span></div><div className="mt-2 h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-cyan-400" style={{width:`${progress}%`}}/></div></div>})}</div><div className="mt-7 flex items-center gap-3 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800"><CheckCircle2/>Progress is saved on this device and starts at zero.</div></div></>
}

export function NotFound() { return <div className="grid min-h-[60vh] place-items-center text-center"><div><p className="text-7xl font-black text-cyan-400">404</p><h1 className="mt-3 text-2xl font-black">Page not found</h1><a href="/ccna-master/" className="mt-5 inline-block font-bold text-cyan-600">Return to dashboard</a></div></div> }
