import type { PracticeQuestion } from './questions'

export const importedQuestions: Record<string, PracticeQuestion[]> = {
  'tcp-udp': [
    { id: 'pdf-tu-2', prompt: 'Which statement best distinguishes TCP from UDP?', choices: ['TCP provides ordered, reliable delivery, while UDP provides connectionless delivery with lower overhead', 'TCP supports only multicast traffic, while UDP supports only unicast traffic', 'TCP is used only across the internet, while UDP is used only on local networks', 'TCP has no error-detection field, while UDP always retransmits lost data'], answer: 0, explanation: 'TCP uses sequencing, acknowledgements, and retransmissions to provide ordered, reliable delivery. UDP is connectionless and has less overhead, making it suitable when low delay is more important than guaranteed delivery.', difficulty: 'easy', tags: ['pdf-import', 'tcp', 'udp', 'reliability'] },
    { id: 'pdf-tu-1', prompt: 'Which statement correctly compares the minimum TCP and UDP header sizes without optional fields?', choices: ['TCP is 20 bytes and UDP is 8 bytes', 'TCP is 8 bytes and UDP is 20 bytes', 'Both are 20 bytes', 'Both are 8 bytes'], answer: 0, explanation: 'A TCP header is at least 20 bytes, while the fixed UDP header is 8 bytes.', difficulty: 'medium', tags: ['pdf-import', 'tcp', 'udp', 'headers'] },
  ],
  'switching-concepts': [
    { id: 'pdf-sc-1', prompt: 'At which OSI layer does a traditional Ethernet switch make its forwarding decisions?', choices: ['Physical layer', 'Data link layer', 'Network layer', 'Transport layer'], answer: 1, explanation: 'A traditional Layer 2 switch operates at the data link layer and forwards Ethernet frames by consulting its MAC address table.', difficulty: 'easy', tags: ['pdf-import', 'layer-2', 'osi'] },
    { id: 'pdf-sc-2', prompt: 'How does a switch learn a dynamic MAC address?', choices: ['It associates the source MAC address of an incoming frame with the receiving port', 'It associates the destination MAC address with every trunk port', 'It requests the address from a neighboring router using CDP', 'It copies the source IP address into the MAC address table'], answer: 0, explanation: 'When a frame arrives, the switch records its source MAC address against the ingress port. The switch later uses this entry to forward frames destined for that MAC address.', difficulty: 'easy', tags: ['pdf-import', 'mac-learning', 'cam-table'] },
    { id: 'pdf-sc-3', prompt: 'Which statement about dynamic MAC address learning on a Layer 2 switch is correct?', choices: ['It is normally enabled by default on active switching interfaces', 'It requires CDP to be enabled on every access port', 'It prevents all denial-of-service attacks', 'It learns addresses from the destination field of a frame'], answer: 0, explanation: 'Dynamic MAC learning is a normal default switching behavior. The switch learns from source MAC addresses; it does not depend on CDP and is not itself a complete security control.', difficulty: 'medium', tags: ['pdf-import', 'mac-learning', 'switching'] },
    { id: 'pdf-sc-4', prompt: 'Which capability allows a Layer 2 switch to divide one physical switched network into multiple logical broadcast domains?', choices: ['IEEE 802.1Q VLAN tagging', 'TCP connection tracking', 'NAT overload', 'OSPF route summarization'], answer: 0, explanation: 'VLANs create separate logical broadcast domains on Layer 2 switches, and IEEE 802.1Q tagging identifies VLAN membership when frames traverse a trunk.', difficulty: 'easy', tags: ['pdf-import', 'layer-2', 'vlans', '802.1q'] },
  ],
  'private-ipv4': [
    { id: 'pdf-pi-1', prompt: 'Why might an organization use RFC 1918 address space on its internal network?', choices: ['It can design an internal addressing plan without obtaining public addresses for every host', 'It makes private addresses directly routable across the public internet', 'It limits every private subnet to a maximum of 254 hosts', 'It guarantees that overlapping networks can communicate without translation'], answer: 0, explanation: 'RFC 1918 space can be used internally without allocation from a regional internet registry. Private addresses are not publicly routable and commonly reach public services through NAT.', difficulty: 'easy', tags: ['pdf-import', 'rfc1918', 'private-addressing'] },
    { id: 'pdf-pi-2', prompt: 'Which characteristic applies to RFC 1918 private IPv4 addresses?', choices: ['They may be used internally without allocation from a regional internet registry', 'They are forwarded globally by internet service providers', 'They automatically provide encrypted internet connectivity', 'They remove the need for unique addresses inside one routing domain'], answer: 0, explanation: 'RFC 1918 reserves private address blocks for internal use without public allocation. Internet routers do not normally route these addresses, and private addressing does not itself provide encryption.', difficulty: 'easy', tags: ['pdf-import', 'rfc1918', 'internet-routing'] },
  ],
  fhrp: [
    { id: 'pdf-fh-1', prompt: 'How does HSRP provide first-hop redundancy to hosts on a LAN?', choices: ['Routers share a virtual IP address and virtual MAC address that hosts use as their default gateway', 'Routers flood every frame through all interfaces in the same VLAN', 'Routers install equal-cost routes in each host routing table', 'Routers divide individual packets across unrelated Layer 2 paths'], answer: 0, explanation: 'HSRP routers form a group that presents one virtual IP and virtual MAC address. Hosts use the virtual IP as their default gateway while an active router forwards traffic and a standby router can take over.', difficulty: 'medium', tags: ['pdf-import', 'hsrp', 'fhrp', 'default-gateway'] },
  ],
  ospfv2: [
    { id: 'pdf-os-1', prompt: 'An OSPF router loses its current route to a destination. Four alternate OSPF paths have costs 20, 30, 40, and 50. Which path is installed?', choices: ['The path with cost 20', 'The path with cost 30', 'The path with cost 40', 'The path with cost 50'], answer: 0, explanation: 'When prefix length and route source are equal, OSPF selects the path with the lowest accumulated cost.', difficulty: 'medium', tags: ['pdf-import', 'ospf', 'metric'] },
  ],
  vlans: [
    { id: 'pdf-vl-1', prompt: 'Which configuration correctly creates router subinterface Ethernet0/0.20 for VLAN 20 with gateway address 10.20.20.1/24?', choices: ['interface Ethernet0/0.20; encapsulation dot1q 20; ip address 10.20.20.1 255.255.255.0', 'interface Ethernet0/0; encapsulation dot1q 20; ip address 10.20.20.1 255.255.255.0', 'interface Ethernet0/0.20; ip address 10.20.20.1 255.255.255.0', 'interface vlan 20; switchport access vlan 20'], answer: 0, explanation: 'Router-on-a-stick requires a logical subinterface, an 802.1Q VLAN association, and the Layer 3 gateway address.', difficulty: 'medium', tags: ['pdf-import', 'router-on-a-stick', 'subinterface'] },
  ],
  'routing-table': [
    { id: 'pdf-rt-1', prompt: 'A router learns the same prefix through OSPF on F0/5 with [110/6292], OSPF on F0/8 with [110/28805], RIP on F0/10 with [120/11], and RIP on F0/18 with [120/4]. Which exit interface is selected?', choices: ['F0/5', 'F0/8', 'F0/10', 'F0/18'], answer: 0, explanation: 'OSPF wins over RIP because 110 is lower than 120. Between the OSPF routes, metric 6292 is lower than 28805, so F0/5 is selected.', difficulty: 'hard', tags: ['pdf-import', 'administrative-distance', 'metric'] },
  ],
  'ipv4-addressing': [
    { id: 'pdf-ip4-1', prompt: 'Hosts 192.168.25.100/25 and 192.168.25.128/25 must communicate directly on one local subnet. Which mask should be configured on both hosts?', choices: ['255.255.255.0', '255.255.255.224', '255.255.255.248', '255.255.255.252'], answer: 0, explanation: 'The original /25 boundary separates the addresses. A /24 mask places both in subnet 192.168.25.0/24.', difficulty: 'medium', tags: ['pdf-import', 'subnetting', 'host-addressing'] },
  ],
  'wireless-security': [
    { id: 'pdf-ws-1', prompt: 'What is the minimum valid length of an ASCII WPA2 pre-shared key on a Cisco wireless LAN controller?', choices: ['6 characters', '8 characters', '12 characters', '64 characters'], answer: 1, explanation: 'A WPA/WPA2 ASCII pre-shared key contains 8 to 63 characters; a hexadecimal key contains exactly 64 hexadecimal characters.', difficulty: 'easy', tags: ['pdf-import', 'wpa2', 'psk'] },
  ],
  'cabling-interfaces': [
    { id: 'pdf-ci-1', prompt: 'Which copper Ethernet cable is traditionally required between two like devices when auto-MDIX is unavailable?', choices: ['Crossover cable', 'Straight-through cable', 'Rollover cable', 'Console cable'], answer: 0, explanation: 'A crossover cable swaps transmit and receive pairs for legacy connections between like Ethernet device types.', difficulty: 'easy', tags: ['pdf-import', 'cabling', 'auto-mdix'] },
    { id: 'pdf-ci-2', prompt: 'Which two characteristics are associated with single-mode fiber? (Choose two.)', choices: ['Supports long-distance links', 'Uses a narrow core', 'Commonly supplies PoE to endpoints', 'Is more vulnerable to electromagnetic interference than copper'], answer: [0, 1], explanation: 'Single-mode fiber uses a small core and is suited to high-bandwidth, long-distance links. Fiber does not carry PoE and is immune to electromagnetic interference.', difficulty: 'medium', tags: ['pdf-import', 'fiber', 'single-mode'] },
    { id: 'pdf-ci-3', prompt: 'When auto-MDIX is unavailable, which copper cable type is traditionally used to connect an Ethernet router interface to a switch interface?', choices: ['Straight-through cable', 'Crossover cable', 'Rollover cable', 'Console cable'], answer: 0, explanation: 'A router and a switch are unlike Ethernet device types, so their transmit and receive pairs align when connected with a straight-through cable. Auto-MDIX removes this traditional requirement on supported interfaces.', difficulty: 'easy', tags: ['pdf-import', 'cabling', 'straight-through', 'auto-mdix'] },
  ],
  trunks: [
    { id: 'pdf-tr-1', prompt: 'Which command places a switch interface in a passive DTP mode that becomes a trunk when the neighbor is configured as trunk or dynamic desirable?', choices: ['switchport mode trunk', 'switchport mode dynamic auto', 'switchport mode dynamic desirable', 'switchport mode access'], answer: 1, explanation: 'Dynamic auto waits for the neighboring port to initiate trunk formation; trunk and dynamic desirable actively form or request a trunk.', difficulty: 'medium', tags: ['pdf-import', 'dtp', 'trunking'] },
  ],
  'topology-architectures': [
    { id: 'pdf-ta-1', prompt: 'How are switches interconnected in a standard spine-and-leaf data-center topology?', choices: ['Every leaf connects to every spine', 'Every leaf connects to only one spine', 'Leaf switches connect in a Layer 2 ring', 'Each spine connects through a central leaf'], answer: 0, explanation: 'Each leaf has an uplink to every spine, providing predictable path length and resilient equal-cost paths.', difficulty: 'easy', tags: ['pdf-import', 'spine-leaf', 'topology'] },
  ],
  'static-routing': [
    { id: 'pdf-sr-1', prompt: 'A router already has a preferred default route through 192.168.2.2. Which command adds a backup default route through 192.168.1.2 with administrative distance 10?', choices: ['ip route 0.0.0.0 0.0.0.0 192.168.1.2 10', 'ip route 0.0.0.0 0.0.0.0 192.168.1.2', 'ip route 192.168.1.2 255.255.255.255 10', 'ip default-gateway 192.168.1.2 10'], answer: 0, explanation: 'A floating static route uses the default prefix plus an administrative distance higher than the primary route.', difficulty: 'medium', tags: ['pdf-import', 'floating-static-route', 'default-route'] },
    { id: 'pdf-sr-2', prompt: 'Which subnet mask identifies an IPv4 static host route to exactly one destination address?', choices: ['255.255.255.255', '255.255.255.252', '255.255.255.0', '0.0.0.0'], answer: 0, explanation: 'An IPv4 host route uses a /32 prefix, represented by mask 255.255.255.255, so the route matches exactly one destination address.', difficulty: 'easy', tags: ['pdf-import', 'static-route', 'host-route', 'prefix-length'] },
  ],
  'cdp-lldp': [
    { id: 'pdf-cl-1', prompt: 'Which global command prevents a Cisco device from advertising its management IP address in LLDP while LLDP remains enabled?', choices: ['no lldp tlv-select management-address', 'no lldp run', 'no lldp transmit', 'no lldp receive'], answer: 0, explanation: 'Disabling selection of the management-address TLV suppresses that information without globally disabling LLDP.', difficulty: 'hard', tags: ['pdf-import', 'lldp', 'tlv'] },
  ],
  'snmp-syslog': [
    { id: 'pdf-sl-1', prompt: 'Which syslog severity number represents Informational messages?', choices: ['0', '2', '4', '6'], answer: 3, explanation: 'Syslog severity 6 is Informational. Lower numbers represent increasingly severe conditions, while 7 is Debugging.', difficulty: 'easy', tags: ['pdf-import', 'syslog', 'severity'] },
  ],
  virtualization: [
    { id: 'pdf-vf-1', prompt: 'Which two characteristics are core capabilities of cloud computing? (Choose two.)', choices: ['On-demand self-service', 'Rapid elasticity', 'Fixed capacity for every tenant', 'Manual provisioning for every request'], answer: [0, 1], explanation: 'Cloud services commonly provide resources on demand and scale them rapidly; fixed capacity and mandatory manual provisioning conflict with those characteristics.', difficulty: 'medium', tags: ['pdf-import', 'cloud', 'virtualization'] },
  ],
}
