import type { PracticeQuestion } from './questions'

type Entry = [topic: string, id: string, prompt: string, correct: string, wrong: [string, string, string], explanation: string, difficulty: NonNullable<PracticeQuestion['difficulty']>]

const entries: Entry[] = [
  ['network-components','m-nc-1','Which device commonly enforces security policy between trusted and untrusted networks?','Next-generation firewall',['Layer 2 hub','Wireless repeater','Patch panel'],'A next-generation firewall filters traffic and can add application awareness and intrusion prevention.','easy'],
  ['topology-architectures','m-ta-1','Which campus design layer aggregates access switches and applies policy?','Distribution layer',['Access layer','Endpoint layer','Internet edge only'],'The distribution layer aggregates access switches and commonly provides routing and policy boundaries.','medium'],
  ['cabling-interfaces','m-ci-1','Which connector is commonly used with Ethernet over twisted-pair copper?','RJ-45',['LC','SC','BNC'],'Copper Ethernet patch cables commonly terminate with 8P8C connectors widely called RJ-45.','easy'],
  ['interface-issues','m-ii-1','An interface is up but its line protocol is down. Which layer should be investigated first?','Data-link layer',['Application layer','Presentation layer','Session layer'],'Up/down commonly indicates that the physical signal exists but a Layer 2 problem remains.','hard'],
  ['tcp-udp','m-tu-1','Which TCP mechanism limits how much unacknowledged data a sender transmits?','Sliding window',['TTL','ARP cache','VLAN tag'],'TCP windowing provides flow control by limiting outstanding unacknowledged data.','medium'],
  ['ipv4-addressing','m-ip4-1','Which prefix provides 14 usable IPv4 host addresses?','/28',['/27','/29','/30'],'A /28 has 16 total addresses and 14 usable host addresses.','medium'],
  ['private-ipv4','m-pi-1','Which address is publicly routable rather than RFC 1918 private?','198.51.100.10',['10.10.10.10','172.20.10.10','192.168.10.10'],'The other three addresses fall within the RFC 1918 private ranges.','easy'],
  ['ipv6-addressing','m-ia-1','How many bits are normally used for the interface ID in an IPv6 /64 subnet?','64',['32','48','128'],'A /64 uses 64 network-prefix bits and 64 interface-ID bits.','easy'],
  ['ipv6-types','m-it-1','Which prefix identifies IPv6 multicast addresses?','FF00::/8',['FE80::/10','FC00::/7','2000::/3'],'All IPv6 multicast addresses begin with FF.','easy'],
  ['ip-parameters','m-ipp-1','Which client setting identifies the router used to reach remote networks?','Default gateway',['DNS suffix','MAC address','Loopback mask'],'A host forwards off-subnet traffic to its configured default gateway.','easy'],
  ['wireless-principles','m-wp-1','What is a major advantage of the 5-GHz band over 2.4 GHz?','More nonoverlapping channels',['Longer range in every environment','No interference','Compatibility with every legacy client'],'5 GHz offers more channel capacity, although its range is often shorter.','medium'],
  ['virtualization','m-vf-1','What separates the control plane from the data plane in software-defined networking?','A centralized controller architecture',['PoE','A crossover cable','NAT overload'],'SDN logically centralizes control while devices continue forwarding traffic in the data plane.','medium'],
  ['switching-concepts','m-sc-1','From which field does a switch learn a MAC-table entry?','Source MAC address',['Destination IP address','EtherType only','FCS value'],'A switch records the source MAC address and incoming port of received frames.','medium'],
  ['vlans','m-vl-1','Which command creates VLAN 30 in global configuration mode?','vlan 30',['interface vlan 30','switchport vlan 30','ip vlan 30'],'The vlan 30 command creates the VLAN and enters VLAN configuration mode.','easy'],
  ['trunks','m-tr-1','What problem can a native VLAN mismatch cause?','Traffic leakage and spanning-tree warnings',['Automatic routing','DHCP encryption','Higher PoE power'],'Different native VLANs can place untagged traffic into different broadcast domains and trigger warnings.','hard'],
  ['cdp-lldp','m-cl-1','Which command enables LLDP globally on Cisco IOS?','lldp run',['cdp run','lldp enable all','service lldp'],'The global lldp run command starts LLDP on supported IOS devices.','easy'],
  ['etherchannel','m-ec-1','Which LACP combination can successfully form an EtherChannel?','Active and passive',['Passive and passive','Auto and auto','On and passive'],'At least one LACP side must be active; two passive ports do not initiate negotiation.','medium'],
  ['rapid-pvst','m-rp-1','Which RSTP port state combines the legacy disabled, blocking, and listening states?','Discarding',['Learning','Forwarding','Designated'],'RSTP uses discarding, learning, and forwarding states.','medium'],
  ['wireless-architectures','m-wa-1','What is the role of a wireless LAN controller?','Centralize AP configuration and policy',['Replace every access switch','Provide copper cabling','Act only as a DNS server'],'A WLC centrally manages lightweight APs, WLANs, security, and radio policy.','easy'],
  ['ap-connections','m-ap-1','Which technology commonly powers an access point through its switch connection?','PoE',['NAT','NTP','HSRP'],'Power over Ethernet carries power and data over the AP Ethernet cable.','easy'],
  ['wireless-gui','m-wg-1','Which WLAN setting maps wireless client traffic to a wired broadcast domain?','VLAN',['RF channel only','NTP stratum','Router ID'],'A WLAN is commonly mapped to a VLAN for wired-network segmentation.','medium'],
  ['routing-table','m-rt-1','Which route source has the lowest default administrative distance?','Directly connected',['OSPF','External BGP','RIP'],'A connected route has administrative distance 0.','medium'],
  ['forwarding-decision','m-fd-1','Which route wins for destination 10.1.1.10: 10.0.0.0/8 or 10.1.1.0/24?','10.1.1.0/24',['10.0.0.0/8','Both are always load-balanced','Neither route'],'The /24 is the longest and therefore most-specific prefix match.','easy'],
  ['static-routing','m-sr-1','Which IPv6 route represents a default route?','::/0',['::1/128','FE80::/10','FF00::/8'],'The zero-length IPv6 prefix matches any destination without a more-specific route.','easy'],
  ['ospfv2','m-os-1','Which OSPF network type elects a DR and BDR by default?','Broadcast multiaccess',['Point-to-point','Loopback','Passive interface'],'Broadcast Ethernet OSPF segments elect a DR and BDR.','medium'],
  ['fhrp','m-fh-1','In HSRP, which router forwards traffic sent to the virtual gateway?','Active router',['Standby switch only','Every host','DNS server'],'The active HSRP router forwards traffic for the virtual IP and MAC address.','easy'],
  ['nat','m-na-1','Which NAT method maps many inside hosts to one public address using ports?','PAT',['Static NAT only','DNS relay','NTP'],'PAT distinguishes simultaneous translations with Layer 4 port numbers.','easy'],
  ['ntp','m-nt-1','Which NTP value indicates distance from an authoritative time source?','Stratum',['Syslog facility','OSPF cost','VLAN ID'],'Lower stratum values are closer to the reference clock.','medium'],
  ['dhcp-dns','m-dd-1','Which DHCP message does a client broadcast first when it has no address?','DHCPDISCOVER',['DHCPACK','DHCPNAK','DNSQUERY'],'The DORA process begins with a client DHCPDISCOVER broadcast.','easy'],
  ['snmp-syslog','m-sl-1','Which SNMP operation is sent unsolicited by an agent to a manager?','Trap',['Get','Set','Walk request'],'A trap asynchronously notifies the manager of an event.','medium'],
  ['qos','m-qo-1','Which QoS technique drops or remarks traffic that exceeds a configured rate?','Policing',['Classification','Queuing only','NAT'],'Policing enforces a rate immediately, commonly by dropping or remarking excess traffic.','medium'],
  ['ssh','m-ss-1','Which VTY command permits SSH while excluding Telnet?','transport input ssh',['login local','ip ssh version 2','service password-encryption'],'transport input ssh restricts inbound VTY transports to SSH.','medium'],
  ['ftp-tftp','m-ft-1','Which protocol uses TCP connections and supports authentication?','FTP',['TFTP','ICMP','ARP'],'FTP uses TCP and supports user authentication; TFTP is a simpler UDP service.','easy'],
  ['security-concepts','m-se-1','Which attack attempts to exhaust a service so legitimate users cannot reach it?','Denial of service',['Reconnaissance only','Data normalization','Configuration backup'],'Denial-of-service attacks target availability by exhausting resources or connectivity.','easy'],
  ['security-program','m-sp-1','What defines acceptable behavior when employees use company technology?','Acceptable-use policy',['Routing table','NAT pool','EtherChannel protocol'],'An acceptable-use policy sets rules for using organizational systems and data.','easy'],
  ['local-passwords','m-lp-1','Which command encrypts many plaintext line passwords in an IOS configuration?','service password-encryption',['enable password','login local','transport output ssh'],'service password-encryption obfuscates supported plaintext passwords in the configuration.','medium'],
  ['password-policy','m-pp-1','Which control most directly reduces risk from a stolen password?','Multi-factor authentication',['Longer lease time','Static routing','PortFast'],'MFA requires another factor even when a password is compromised.','easy'],
  ['ipsec-vpn','m-iv-1','Which IPsec protocol provides confidentiality by encrypting payload data?','ESP',['ARP','CDP','LLDP'],'Encapsulating Security Payload provides encryption and can also provide integrity.','medium'],
  ['acls','m-ac-1','What wildcard mask matches exactly one IPv4 host?','0.0.0.0',['0.0.0.255','255.255.255.255','0.0.255.255'],'All-zero wildcard bits require every address bit to match.','medium'],
  ['layer2-security','m-ls-1','Which feature validates ARP messages against trusted bindings?','Dynamic ARP Inspection',['PortFast','NAT overload','OSPF'],'DAI uses trusted bindings, often from DHCP snooping, to reject invalid ARP traffic.','medium'],
  ['aaa','m-aa-1','Which AAA function determines what an authenticated user may access?','Authorization',['Authentication','Accounting','Availability'],'Authorization assigns permitted services and commands after identity is verified.','easy'],
  ['wireless-security','m-ws-1','Which WPA2-Personal mechanism authenticates clients without a RADIUS server?','Pre-shared key',['802.1X only','Open authentication','WEP key rotation'],'WPA2-Personal uses a shared passphrase rather than enterprise AAA.','easy'],
  ['automation-impact','m-au-1','What is configuration drift?','Unintended differences between intended and actual configurations',['A routing loop','Wireless attenuation','Clock synchronization'],'Automation and source-controlled templates help detect and prevent configuration drift.','medium'],
  ['controller-networking','m-cn-1','Which API type exposes controller services to applications?','Northbound API',['Southbound API','Console line','Data-plane ASIC'],'Northbound APIs connect controller capabilities to applications and automation systems.','medium'],
  ['ai-ml','m-am-1','Which operational use best fits anomaly-detection machine learning?','Identify unusual telemetry patterns',['Replace all routing protocols','Generate Ethernet voltage','Assign cable pinouts'],'Anomaly models learn normal patterns and flag significant deviations.','medium'],
  ['rest-apis','m-re-1','Which HTTP method normally performs a partial resource update?','PATCH',['GET','DELETE','HEAD'],'PATCH applies partial modifications, whereas PUT commonly replaces a representation.','medium'],
  ['config-management','m-cm-1','Which format is commonly used for an Ansible playbook?','YAML',['JPEG','PCAP','ASN.1 only'],'Ansible playbooks are normally expressed in YAML.','easy'],
  ['json','m-js-1','Which JSON value represents the absence of a value?','null',['undefined','None','void'],'null is a valid JSON literal; undefined is not.','easy'],
]

function makeQuestion([, id, prompt, correct, wrong, explanation, difficulty]: Entry): PracticeQuestion {
  return { id, prompt, choices: [correct, ...wrong], answer: 0, explanation, difficulty, tags: ['mastery', 'blueprint'] }
}

export const masteryQuestions: Record<string, PracticeQuestion[]> = {}
for (const entry of entries) masteryQuestions[entry[0]] = [...(masteryQuestions[entry[0]] ?? []), makeQuestion(entry)]
